figure("Name", "Graphics", "NumberTitle", "off");
subplot(2, 2, 1);
x = linspace(-10, 10, 1000);
y = x + (1 ./(x.^2));
plot(x, y);
y = (x.*2)./(1 + x.^2);
subplot(2, 2, 2);
plot(x, y);
subplot(2, 2, 3);
y = x.*sin(x.*pi);
plot(x, y);
hold on;
plot(x, x, x, -x);
hold off;
subplot(2,2,4);
m = 7; n = 17; a = 1 / 2; b = 1 / 3;
t = -5:0.01:5;
x = cos(t) + a * cos(m * t) + b * sin(n * t);
y = sin(t) + a * sin(m * t) + b * cos(n * t);
plot(x, y);
